// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: stage_primer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StagePrimer_Jog_FullMethodName                = "/stage_primer.StagePrimer/Jog"
	StagePrimer_JogOffset_FullMethodName          = "/stage_primer.StagePrimer/JogOffset"
	StagePrimer_GetPosition_FullMethodName        = "/stage_primer.StagePrimer/GetPosition"
	StagePrimer_DeployCommandTable_FullMethodName = "/stage_primer.StagePrimer/DeployCommandTable"
	StagePrimer_MonitorFaults_FullMethodName      = "/stage_primer.StagePrimer/MonitorFaults"
	StagePrimer_SetVacuum_FullMethodName          = "/stage_primer.StagePrimer/SetVacuum"
	StagePrimer_GetUSBDevices_FullMethodName      = "/stage_primer.StagePrimer/GetUSBDevices"
	StagePrimer_GetConfig_FullMethodName          = "/stage_primer.StagePrimer/GetConfig"
	StagePrimer_SetConfig_FullMethodName          = "/stage_primer.StagePrimer/SetConfig"
)

// StagePrimerClient is the client API for StagePrimer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StagePrimerClient interface {
	// Jog moves a stage to an absolute Z position
	Jog(ctx context.Context, in *JogRequest, opts ...grpc.CallOption) (*Empty, error)
	// JogOffset moves a stage by a relative Z offset
	JogOffset(ctx context.Context, in *JogOffsetRequest, opts ...grpc.CallOption) (*Empty, error)
	// GetPosition retrieves the current Z position of a stage
	GetPosition(ctx context.Context, in *GetPositionRequest, opts ...grpc.CallOption) (*GetPositionResponse, error)
	// DeployCommandTable deploys command table configuration to a stage
	DeployCommandTable(ctx context.Context, in *DeployCommandTableRequest, opts ...grpc.CallOption) (*Empty, error)
	// MonitorFaults streams fault notifications from all drives
	MonitorFaults(ctx context.Context, in *Empty, opts ...grpc.CallOption) (StagePrimer_MonitorFaultsClient, error)
	// SetVacuum controls vacuum for a stage
	SetVacuum(ctx context.Context, in *SetVacuumRequest, opts ...grpc.CallOption) (*Empty, error)
	// GetUSBDevices lists connected USB devices
	GetUSBDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetUSBDevicesResponse, error)
	// GetConfig retrieves the current stage_primer configuration
	GetConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// SetConfig updates the stage_primer configuration
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*Empty, error)
}

type stagePrimerClient struct {
	cc grpc.ClientConnInterface
}

func NewStagePrimerClient(cc grpc.ClientConnInterface) StagePrimerClient {
	return &stagePrimerClient{cc}
}

func (c *stagePrimerClient) Jog(ctx context.Context, in *JogRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, StagePrimer_Jog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagePrimerClient) JogOffset(ctx context.Context, in *JogOffsetRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, StagePrimer_JogOffset_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagePrimerClient) GetPosition(ctx context.Context, in *GetPositionRequest, opts ...grpc.CallOption) (*GetPositionResponse, error) {
	out := new(GetPositionResponse)
	err := c.cc.Invoke(ctx, StagePrimer_GetPosition_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagePrimerClient) DeployCommandTable(ctx context.Context, in *DeployCommandTableRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, StagePrimer_DeployCommandTable_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagePrimerClient) MonitorFaults(ctx context.Context, in *Empty, opts ...grpc.CallOption) (StagePrimer_MonitorFaultsClient, error) {
	stream, err := c.cc.NewStream(ctx, &StagePrimer_ServiceDesc.Streams[0], StagePrimer_MonitorFaults_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &stagePrimerMonitorFaultsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StagePrimer_MonitorFaultsClient interface {
	Recv() (*FaultNotification, error)
	grpc.ClientStream
}

type stagePrimerMonitorFaultsClient struct {
	grpc.ClientStream
}

func (x *stagePrimerMonitorFaultsClient) Recv() (*FaultNotification, error) {
	m := new(FaultNotification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stagePrimerClient) SetVacuum(ctx context.Context, in *SetVacuumRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, StagePrimer_SetVacuum_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagePrimerClient) GetUSBDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetUSBDevicesResponse, error) {
	out := new(GetUSBDevicesResponse)
	err := c.cc.Invoke(ctx, StagePrimer_GetUSBDevices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagePrimerClient) GetConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, StagePrimer_GetConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagePrimerClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, StagePrimer_SetConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StagePrimerServer is the server API for StagePrimer service.
// All implementations must embed UnimplementedStagePrimerServer
// for forward compatibility
type StagePrimerServer interface {
	// Jog moves a stage to an absolute Z position
	Jog(context.Context, *JogRequest) (*Empty, error)
	// JogOffset moves a stage by a relative Z offset
	JogOffset(context.Context, *JogOffsetRequest) (*Empty, error)
	// GetPosition retrieves the current Z position of a stage
	GetPosition(context.Context, *GetPositionRequest) (*GetPositionResponse, error)
	// DeployCommandTable deploys command table configuration to a stage
	DeployCommandTable(context.Context, *DeployCommandTableRequest) (*Empty, error)
	// MonitorFaults streams fault notifications from all drives
	MonitorFaults(*Empty, StagePrimer_MonitorFaultsServer) error
	// SetVacuum controls vacuum for a stage
	SetVacuum(context.Context, *SetVacuumRequest) (*Empty, error)
	// GetUSBDevices lists connected USB devices
	GetUSBDevices(context.Context, *Empty) (*GetUSBDevicesResponse, error)
	// GetConfig retrieves the current stage_primer configuration
	GetConfig(context.Context, *Empty) (*GetConfigResponse, error)
	// SetConfig updates the stage_primer configuration
	SetConfig(context.Context, *SetConfigRequest) (*Empty, error)
	mustEmbedUnimplementedStagePrimerServer()
}

// UnimplementedStagePrimerServer must be embedded to have forward compatible implementations.
type UnimplementedStagePrimerServer struct {
}

func (UnimplementedStagePrimerServer) Jog(context.Context, *JogRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Jog not implemented")
}
func (UnimplementedStagePrimerServer) JogOffset(context.Context, *JogOffsetRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JogOffset not implemented")
}
func (UnimplementedStagePrimerServer) GetPosition(context.Context, *GetPositionRequest) (*GetPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPosition not implemented")
}
func (UnimplementedStagePrimerServer) DeployCommandTable(context.Context, *DeployCommandTableRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployCommandTable not implemented")
}
func (UnimplementedStagePrimerServer) MonitorFaults(*Empty, StagePrimer_MonitorFaultsServer) error {
	return status.Errorf(codes.Unimplemented, "method MonitorFaults not implemented")
}
func (UnimplementedStagePrimerServer) SetVacuum(context.Context, *SetVacuumRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVacuum not implemented")
}
func (UnimplementedStagePrimerServer) GetUSBDevices(context.Context, *Empty) (*GetUSBDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUSBDevices not implemented")
}
func (UnimplementedStagePrimerServer) GetConfig(context.Context, *Empty) (*GetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedStagePrimerServer) SetConfig(context.Context, *SetConfigRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedStagePrimerServer) mustEmbedUnimplementedStagePrimerServer() {}

// UnsafeStagePrimerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StagePrimerServer will
// result in compilation errors.
type UnsafeStagePrimerServer interface {
	mustEmbedUnimplementedStagePrimerServer()
}

func RegisterStagePrimerServer(s grpc.ServiceRegistrar, srv StagePrimerServer) {
	s.RegisterService(&StagePrimer_ServiceDesc, srv)
}

func _StagePrimer_Jog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePrimerServer).Jog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StagePrimer_Jog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePrimerServer).Jog(ctx, req.(*JogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagePrimer_JogOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JogOffsetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePrimerServer).JogOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StagePrimer_JogOffset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePrimerServer).JogOffset(ctx, req.(*JogOffsetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagePrimer_GetPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePrimerServer).GetPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StagePrimer_GetPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePrimerServer).GetPosition(ctx, req.(*GetPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagePrimer_DeployCommandTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployCommandTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePrimerServer).DeployCommandTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StagePrimer_DeployCommandTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePrimerServer).DeployCommandTable(ctx, req.(*DeployCommandTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagePrimer_MonitorFaults_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StagePrimerServer).MonitorFaults(m, &stagePrimerMonitorFaultsServer{stream})
}

type StagePrimer_MonitorFaultsServer interface {
	Send(*FaultNotification) error
	grpc.ServerStream
}

type stagePrimerMonitorFaultsServer struct {
	grpc.ServerStream
}

func (x *stagePrimerMonitorFaultsServer) Send(m *FaultNotification) error {
	return x.ServerStream.SendMsg(m)
}

func _StagePrimer_SetVacuum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVacuumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePrimerServer).SetVacuum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StagePrimer_SetVacuum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePrimerServer).SetVacuum(ctx, req.(*SetVacuumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagePrimer_GetUSBDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePrimerServer).GetUSBDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StagePrimer_GetUSBDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePrimerServer).GetUSBDevices(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagePrimer_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePrimerServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StagePrimer_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePrimerServer).GetConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagePrimer_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePrimerServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StagePrimer_SetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePrimerServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StagePrimer_ServiceDesc is the grpc.ServiceDesc for StagePrimer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StagePrimer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stage_primer.StagePrimer",
	HandlerType: (*StagePrimerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Jog",
			Handler:    _StagePrimer_Jog_Handler,
		},
		{
			MethodName: "JogOffset",
			Handler:    _StagePrimer_JogOffset_Handler,
		},
		{
			MethodName: "GetPosition",
			Handler:    _StagePrimer_GetPosition_Handler,
		},
		{
			MethodName: "DeployCommandTable",
			Handler:    _StagePrimer_DeployCommandTable_Handler,
		},
		{
			MethodName: "SetVacuum",
			Handler:    _StagePrimer_SetVacuum_Handler,
		},
		{
			MethodName: "GetUSBDevices",
			Handler:    _StagePrimer_GetUSBDevices_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _StagePrimer_GetConfig_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _StagePrimer_SetConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MonitorFaults",
			Handler:       _StagePrimer_MonitorFaults_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "stage_primer.proto",
}
